"""Migrations for the 2025 Q4 Authenticator release - version 2: adding nonce columns for complex oidc

Revision ID: 25Q4v2
Revises: 25Q4
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25Q4v2'
down_revision = '25Q4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))

    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    # ### end Alembic commands ###
